---

- name: Clean apt
  become: true
  command: apt -qq clean

- name: Clean caches & tmp dirs
  become: true
  block:
    - name: Check caches & temp files
      find:
        file_type: any
        paths:
          - /var/lib/apt/lists
          - /tmp
      register: reg_caches

#    - name: Check ssh host keys
#      find:
#        patterns: ssh_host_*
#        paths: /etc/ssh
#      register: reg_ssh_host_keys

    - name: Clean found items
      when: reg_caches.matched > 0
#      with_items: "{{ reg_caches.files + reg_ssh_host_keys.files }}"
      with_items: "{{ reg_caches.files }}"
      file:
        path: "{{ item.path }}"
        state: absent

- name: Fill free space with zeroes
  become: true
  shell: cat /dev/zero > wipefile; rm -f wipefile
  async: 1800  # Prevent SSH connections timing out waiting for cleanup
  poll: 30
  tags:
    - wipe_disk_zeroes

- name: Reset the machine-id which is used for DHCP IP assign
  become: true
  copy:
    content: ''
    dest: /etc/machine-id
