---
- name: Delete hibernate sleepimage file
  file:
    state: absent
    path: /var/vm/sleepimage
  become: true

- name: Delete bash history
  file:
    state: absent
    path: /Users/{{ ansible_user }}/{{ item }}
  loop:
    - .bash_history
    - .bash_sessions

- name: Empty trash
  ignore_errors: true
  file:
    state: absent
    path: /Users/{{ ansible_user }}/.Trash

- name: Clean caches & tmp dirs
  become: true
  block:
    - name: Check caches & temp files
      find:
        file_type: any
        paths:
          - /Library/Caches
          - /Users/{{ ansible_user }}/Library/Caches
          - /tmp
      register: reg_caches

    - name: Check ssh host keys
      find:
        patterns: ssh_host_*
        paths: /etc/ssh
      register: reg_ssh_host_keys

    - name: Clean found items
      when: reg_caches.matched > 0
      # Caches cleaning on MacOS 11.6 is harder with SIP activated so some folders can't be
      # accessible, so ignoring them in case they producing an error
      ignore_errors: true
      with_items: "{{ reg_caches.files + reg_ssh_host_keys.files }}"
      file:
        path: "{{ item.path }}"
        state: absent

- name: Fill free space with zeroes
  become: true
  shell: cat /dev/zero > wipefile; rm -f wipefile
  async: 1800  # Prevent SSH connections timing out waiting for cleanup
  poll: 30
  tags:
    - wipe_disk_zeroes
