---

- name: Stop the VMWare services for now to be able to clean up the tmp folder
  ignore_errors: true  # don't fail in case those services are not here
  win_service:
    name: '{{ item }}'
    start_mode: auto
    state: stopped
  with_items:
    - VMTools
    - vmvss

- name: Stop vmtoolsd.exe - it's not available through services
  ignore_errors: true  # don't fail in case those services are not here
  win_shell: Stop-Process -Name vmtoolsd -Force

- name: Clean caches & tmp dirs and ssh host keys/auth
  win_shell: Remove-Item '{{ item }}' -force -recurse
  with_items:
    - C:\tmp\*
    - C:\Windows\Temp\*
    - C:\Windows\Prefetch\*
    - C:\Documents and Settings\*\Local Settings\temp\*
    - C:\Users\*\Appdata\Local\Temp\*
    - C:\ProgramData\ssh\ssh_host*
    - C:\ProgramData\ssh\*authorized_keys

- name: Clean event log
  win_shell: Get-EventLog -List | ForEach-Object { Clear-EventLog -LogName $_.Log }

- name: Accept sdelete eula
  win_regedit:
    path: HKCU:\Software\Sysinternals\SDelete
    name: EulaAccepted
    data: 1
    type: dword
  tags:
    - wipe_disk_zeroes

- name: Compact the disk
  win_command: 'C:\util\sdelete\sdelete.exe -q -z C:'
  async: 1800  # Prevent connections timing out waiting for compact
  poll: 30
  tags:
    - wipe_disk_zeroes
