---

- name: Stop the VMWare service for now to be able to clean up the tmp folder
  ignore_errors: true
  win_service:
    name: VMTools
    start_mode: auto
    state: stopped

- name: Clean caches & tmp dirs
  changed_when: true
  win_shell: Remove-Item '{{ item }}' -force -recurse
  with_items:
    - C:\tmp\*
    - C:\Windows\Temp\*
    - C:\Windows\Prefetch\*
    - C:\Documents and Settings\*\Local Settings\temp\*
    - C:\Users\*\Appdata\Local\Temp\*

- name: Clean event log
  changed_when: true
  win_shell: Get-EventLog -List | ForEach-Object { Clear-EventLog -LogName $_.Log }

- name: Compact the disk
  changed_when: true
  win_command: 'C:\util\sdelete\sdelete.exe /accepteula -z C:'
