---
- name: Validate required variables
  when: item not in vars or vars[item] | length == 0
  with_items: "{{ required_vars }}"
  fail:
    msg: Variable '{{ item }}' is not defined

- name: Execute on Linux
  include_tasks: linux.yml
  when: ansible_system == 'Linux'

- name: Execute on MacOS
  include_tasks: macos.yml
  when: ansible_system == 'Darwin'

- name: Execute on Windows
  include_tasks: windows.yml
  when: ansible_system == 'Win32NT'
