---
- name: Get tool on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ jre_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ vmtools_vmware_archive_local }}"
        dest: /tmp/{{ vmtools_vmware_archive_local }}

    - name: Download cmd tools if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ vmtools_vmware_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ vmtools_vmware_archive_local }}"
        mode: "0440"
        checksum: "{{ vmtools_vmware_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ vmtools_vmware_archive_local }}"
        dest: /tmp/{{ vmtools_vmware_archive_local }}

- name: Install VMware tools from the pkg archive
  command: installer -pkg /tmp/{{ vmtools_vmware_archive_local }} -target /
  become: true
  changed_when: true
