---
- name: Download VMWare tools package to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ vmtools_mac_vmware_download_url }}'
    download_checksum: '{{ vmtools_mac_vmware_download_checksum }}'

- name: Install VMware tools from the pkg archive
  command: installer -pkg '{{ download_path }}' -target /
  become: true
  changed_when: true
  register: reg_vmtools_result
  ignore_errors: true

- name: MacOS 11 will not allow to simple install kext even with disabled SIP
  when: reg_vmtools_result.rc != 0
  block:
    - name: Execute vncdo in case installation failed to allow kernel extensions
      include_role:
        name: vncdo
      vars:
        vncdo_template: mac/system_preferences_security_vendor_allow.vdo

    # Rerun the download and installation
    - name: Download VMWare tools package to the environment
      include_role:
        name: download
      vars:
        download_url: '{{ vmtools_mac_vmware_download_url }}'
        download_checksum: '{{ vmtools_mac_vmware_download_checksum }}'

    - name: Install VMware tools from the pkg archive
      command: installer -pkg '{{ download_path }}' -target /
      become: true
      changed_when: true
