---
- name: Get tool on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ vmtools_vmware_mac_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ vmtools_vmware_mac_archive_local }}"
        dest: /tmp/{{ vmtools_vmware_mac_archive_local }}

    - name: Download cmd tools if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ vmtools_vmware_mac_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ vmtools_vmware_mac_archive_local }}"
        mode: "0440"
        checksum: "{{ vmtools_vmware_mac_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ vmtools_vmware_mac_archive_local }}"
        dest: /tmp/{{ vmtools_vmware_mac_archive_local }}

- name: Install VMware tools from the pkg archive
  command: installer -pkg /tmp/{{ vmtools_vmware_mac_archive_local }} -target /
  become: true
  changed_when: true
  register: reg_vmtools_result
  ignore_errors: true

- name: MacOS 11 will not allow to simple install kext even with disabled SIP
  when: reg_vmtools_result.rc != 0
  block:
    - name: Execute vncdo in case installation failed to allow kernel extensions
      include_role:
        name: vncdo
      vars:
        vncdo_template: mac/system_preferences_security_vendor_allow.vdo

    # Rerun the copy and installation
    - name: Create archive directory
      file:
        path: /tmp/{{ vmtools_vmware_mac_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      copy:
        src: "{{ vmtools_vmware_mac_archive_local }}"
        dest: /tmp/{{ vmtools_vmware_mac_archive_local }}

    - name: Install VMware tools from the pkg archive
      command: installer -pkg /tmp/{{ vmtools_vmware_mac_archive_local }} -target /
      become: true
      changed_when: true
