---
- name: Download VMWare tools package to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ vmtools_vmware_win_download_url }}'
    download_sum: '{{ vmtools_vmware_win_download_sum }}'

# In case you see errors - check the log file:
# C:\Users\packer\AppData\Local\Temp\vminst.log
- name: Install VMware tools
  ignore_unreachable: true  # Will cause UNREACHABLE error, so skip it
  win_shell: '{{ download_path }} /S /v "/qn REBOOT=ReallySuppress"'  # Using win shell here to properly parse quotes
  args:
    executable: cmd
  register: reg_vmtools_result
  failed_when: reg_vmtools_result.rc != 3010  # Describes reboot is needed

- name: Reboot the VM after VM tools installation
  win_reboot:

- name: Wait till connection will be available
  wait_for_connection:
    delay: 20

- name: Execute vncdo to login as user to complete the vmware tools installation
  include_role:
    name: vncdo
  vars:
    vncdo_template: win/login.vdo

- name: Check the VMWare tools was installed correctly
  win_wait_for_process:
    process_name_exact: '{{ item }}'
    timeout: 20
  with_items:
    - vmtoolsd
    - vm3dservice
