---
- name: Get VMWare tools on VM
  block:
    - name: Create archive directory
      win_file:
        path: C:\tmp\{{ vmtools_vmware_win_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      win_copy:
        src: "{{ vmtools_vmware_win_archive_local }}"
        dest: C:\tmp\{{ vmtools_vmware_win_archive_local }}

    - name: Download archive if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      win_get_url:
        url: "{{ vmtools_vmware_win_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ vmtools_vmware_win_archive_local }}"
        mode: "0440"
        checksum: "{{ vmtools_vmware_win_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      win_copy:
        src: "{{ vmtools_vmware_win_archive_local }}"
        dest: C:\tmp\{{ vmtools_vmware_win_archive_local }}

- name: Install VMware tools
  changed_when: true
  register: reg_vmtools_result
  failed_when: reg_vmtools_result.rc != 3010
  win_command: C:\tmp\{{ vmtools_vmware_win_archive_local }} /qn REBOOT=R ADDLOCAL=ALL REMOVE=Hgfs
  args:
    creates: C:\Program Files\VMware\VMware Tools\vmtoolsd.exe
