---
- name: Download VMWare tools package to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ vmtools_vmware_win_download_url }}'
    download_sum: '{{ vmtools_vmware_win_download_sum }}'

# In case you see errors - check the log file:
# C:\Users\packer\AppData\Local\Temp\vminst.log
- name: Install VMware tools
  register: reg_vmtools_result
  failed_when: reg_vmtools_result.rc != 1641  # Reboot will cause this exit code
  win_command: '{{ download_path }} /qn ADDLOCAL=ALL'

- name: Wait additional time before connecting back
  wait_for_connection:
    delay: 20

- name: Execute vncdo to login as user to complete the vmware tools installation
  include_role:
    name: vncdo
  vars:
    vncdo_template: win/login.vdo

- name: Check the VMWare tools was installed correctly
  win_wait_for_process:
    process_name_exact: '{{ item }}'
    timeout: 20
  with_items:
    - vmtoolsd
    - vm3dservice
