---
xcode_download_url: '{{ xcode_version_122_download_url }}'
xcode_download_checksum: '{{ xcode_version_122_checksum }}'

xcode_extraction_timeout: 3000  # Right now ~941sec
xcode_install_path: /Applications

xcode_cmd_download_url: '{{ xcode_version_cmd_122_download_url }}'
xcode_cmd_download_checksum: '{{ xcode_version_cmd_122_download_checksum }}'
