---
- name: Download command line tools DMG to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ xcode_cmd_download_url }}'
    download_checksum: '{{ xcode_cmd_download_checksum }}'

- name: Mount cmd tools DMG file
  command: hdiutil attach '{{ download_path }}' -nobrowse -mountpoint /tmp/clt_xcode
  become: true

- name: Find pkg files in the mounted directory
  find:
    file_type: file
    paths: /tmp/clt_xcode
    patterns: "*.pkg"
  register: reg_pkgs

- name: Install cmd tools from found pkgs
  command: installer -pkg '{{ item.path }}' -target /
  with_items: "{{ reg_pkgs.files }}"
  become: true

- name: Umount cmd tools DMG file
  become: true
  command: hdiutil detach /tmp/clt_xcode
