---
- name: Get command line tools on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ xcode_cmd_archive_local | dirname }}
        state: directory

    - name: Get cmd tools from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ xcode_cmd_archive_local }}"
        dest: /tmp/{{ xcode_cmd_archive_local }}

    - name: Download cmd tools if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ xcode_cmd_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ xcode_cmd_archive_local }}"
        mode: "0440"
        checksum: "{{ xcode_cmd_archive_checksum }}"

    - name: Get cmd tools from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ xcode_cmd_archive_local }}"
        dest: /tmp/{{ xcode_cmd_archive_local }}

- name: Mount cmd tools DMG file
  command: hdiutil attach '/tmp/{{ xcode_cmd_archive_local }}' -nobrowse -mountpoint /tmp/clt_xcode
  become: true
  changed_when: true

- name: Find pkg files in the mounted directory
  find:
    file_type: file
    paths: /tmp/clt_xcode
    patterns: "*.pkg"
  register: reg_pkgs

- name: Install cmd tools from found pkgs
  command: installer -pkg '{{ item.path }}' -target /
  with_items: "{{ reg_pkgs.files }}"
  become: true
  changed_when: true

- name: Umount cmd tools DMG file
  become: true
  command: hdiutil detach /tmp/clt_xcode
  changed_when: true
