---
- name: Install command line tools first
  import_tasks: cmd_tools.yml

# Xcode needs command line tools to accept license, otherwise will fail with no xcrun
- name: Install xcode
  import_tasks: xcode.yml
