---
- name: Install command line tools first
  import_tasks: cmd_tools.yml

# Xcode needs command line tools to accept license, otherwise will fail with no xcrun
- name: Install xcode
  import_tasks: xcode.yml

# Going through the simruntime installs list
- name: Install simruntimes
  with_items: "{{ xcode_simruntime_install }}"
  loop_control:
    loop_var: ext_item
  include_tasks: simruntime.yml
  vars:
    simruntime_platform: '{{ ext_item.platform }}'
    simruntime_version: '{{ ext_item.version|default("") }}'
    simruntime_check: '{{ ext_item.check|default([]) }}'
