---
- name: Get Xcode on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ xcode_archive_local | dirname }}
        state: directory

    - name: Get Xcode from local files
      copy:
        src: "{{ xcode_archive_local }}"
        dest: /tmp/{{ xcode_archive_local }}
      ignore_errors: true

    - name: Download Xcode if local file is not available
      get_url:
        url: "{{ xcode_archive_url }}"
        dest: /tmp/{{ xcode_archive_local }}
        mode: "0440"
        checksum: "{{ xcode_archive_checksum }}"

- name: Install Xcode from XIP file Location
  command: xip --expand /tmp/{{ xcode_archive_local }}
  args:
    chdir: /Applications
  async: "{{ xcode_archive_extraction_timeout }}"  # Prevent SSH connections timing out waiting for extraction
  poll: 5
  changed_when: true

- name: Accept License Agreement
  command: xcodebuild -license accept
  become: true
  changed_when: true

- name: Run Xcode first launch
  command: xcodebuild -runFirstLaunch
  become: true
  changed_when: true
