---
- name: Get Xcode on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ xcode_archive_local | dirname }}
        state: directory

    - name: Get Xcode from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ xcode_archive_local }}"
        dest: /tmp/{{ xcode_archive_local }}

    - name: Download Xcode if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ xcode_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ xcode_archive_local }}"
        mode: "0440"
        checksum: "{{ xcode_archive_checksum }}"

    - name: Get Xcode from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ xcode_archive_local }}"
        dest: /tmp/{{ xcode_archive_local }}

- name: Install Xcode from XIP file Location
  become: true
  command: xip --expand /tmp/{{ xcode_archive_local }}
  args:
    chdir: /Applications
  async: "{{ xcode_archive_extraction_timeout }}"  # Prevent SSH connections timing out waiting for extraction
  poll: 30
  changed_when: true

- name: Accept License Agreement
  command: xcodebuild -license accept
  become: true
  changed_when: true

- name: Run Xcode first launch
  command: xcodebuild -runFirstLaunch
  become: true
  changed_when: true
