---
- name: Download XCode archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ xcode_download_url }}'
    download_checksum: '{{ xcode_download_checksum }}'

- name: Install Xcode from XIP file Location
  become: true
  command: xip --expand '{{ download_path }}'
  args:
    chdir: /Applications
  async: "{{ xcode_extraction_timeout }}"  # Prevent SSH connections timing out waiting for extraction
  poll: 30
  changed_when: true

- name: Accept License Agreement
  command: xcodebuild -license accept
  become: true
  changed_when: true

- name: Run Xcode first launch
  command: xcodebuild -runFirstLaunch
  become: true
  changed_when: true
