---
vmtools_vmware_mac_download_url: https://artifact-storage/aquarium/files/mac/VMware-tools-12.1.0-20219665.iso
vmtools_vmware_mac_download_sum: sha256:a7f36778890e0791c2919a3eadb56a848c5a2b5126dba309482f5b63376a9649

vmtools_vmware_win_download_url: https://artifact-storage/aquarium/files/win/VMware-tools-12.2.0-21223074-x86_64.exe
vmtools_vmware_win_download_sum: sha256:fcaf876d62c08a30cf51581228df0d24710b16ff645423b8f7e98a75e46119ab

required_vars:
  - vmtools_vm_type  # Which tool to install
