---
- name: Get Vault on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ vault_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ vault_archive_local }}"
        dest: /tmp/{{ vault_archive_local }}

    - name: Download archive if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ vault_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ vault_archive_local }}"
        mode: "0440"
        checksum: "{{ vault_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ vault_archive_local }}"
        dest: /tmp/{{ vault_archive_local }}

- name: Unzip vault
  become: true
  unarchive:
    src: /tmp/{{ vault_archive_local }}
    dest: /usr/local/
    remote_src: true
