---
- name: Download Vault archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ vault_mac_download_url }}'
    download_checksum: '{{ vault_mac_download_checksum }}'

- name: Unzip vault
  become: true
  unarchive:
    src: '{{ download_path }}'
    dest: /usr/local/
    remote_src: true
