---
- name: Get JRE on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ jre_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ jre_archive_local }}"
        dest: /tmp/{{ jre_archive_local }}

    - name: Download archive if local file is not available
      when: reg_copy_local_file.state != "success"
      delegate_to: localhost
      get_url:
        url: "{{ jre_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ jre_archive_local }}"
        mode: "0440"
        checksum: "{{ jre_archive_checksum }}"

    - name: Get archive from the localhost files
      copy:
        src: "{{ jre_archive_local }}"
        dest: /tmp/{{ jre_archive_local }}

- name: Create extract directory
  become: true
  file:
    path: "{{ jre_extract_path }}"
    state: directory

# Uses BSD tar, GNU will require --wildcards in addition
- name: Unpack only bin & lib from archive to directory
  become: true
  command: >
    tar -C "{{ jre_extract_path }}" --strip-components=3 -xf "/tmp/{{ jre_archive_local }}"
    "*/Contents/Home/bin" "*/Contents/Home/lib"
  args:
    warn: false  # Unarchive requires GNU tar that is not installed on macos by default
  changed_when: true
