---
- name: Validate required variables
  when: item not in vars or vars[item]
  with_items: "{{ required_vars }}"
  fail:
    msg: Variable '{{ item }}' is not defined

- name: Execute on MacOS
  import_tasks: macos.yml
  when: ansible_system == 'Darwin'
