---
- name: Download JRE archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ jre_win_download_url }}'
    download_checksum: '{{ jre_win_download_checksum }}'

- name: Create JRE unpack directory
  win_file:
    path: "{{ jre_extract_path }}"
    state: directory

# Uses BSD tar, GNU will require --wildcards in addition
- name: Unpack only bin & lib from archive to directory
  changed_when: true
  win_shell: >
    tar -C "{{ jre_extract_path }}" --strip-components=1 -xf '{{ download_path }}'
    "*/bin" "*/lib"
  args:
    warn: false  # Unarchive requires GNU tar that is not installed on windows by default

- name: Check java binary was unpacked properly
  win_stat:
    path: '{{ jre_extract_path }}\bin\java.exe'
  register: reg_jre_bin_file
  failed_when: not reg_jre_bin_file.stat.exists
