---
min_packer_version: 1.7.9
variables:
  # All the variables are set by the build_image.sh script based on the path
  image_name: image
  parent_name: parent_image
  out_full_path: "{{ env `PWD` }}/out"
  parent_version: parent_version

builders:
  - type: docker
    image: "aquarium/{{ user `parent_name` }}:{{ user `parent_version` }}"
    pull: false
    commit: true

provisioners:
  - type: ansible
    command: "{{ user `bait_path` }}/scripts/run_ansible.sh"
    playbook_file: "{{ user `bait_path` }}/playbooks/build_essential_image.yml"
    extra_arguments:
      - --skip-tags
      - wipe_disk_zeroes
      - -e
      - ansible_become=false  # We already root here

post-processors:
  - type: docker-tag
    repository: "aquarium/{{ user `image_name` }}"
    tags: original
