---
- name: Set GMT timezone
  include_tasks: macos_systemsetup.yml
  vars:
    key: timezone
    value: GMT

- name: Disable system sleep
  include_tasks: macos_systemsetup.yml
  vars:
    key: "{{ item }}"
    value: Never
  with_items:
    - computersleep
    - displaysleep
    - harddisksleep

- name: Disable automatic download and install of the updates
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: "{{ item }}"
    type: bool
    value: false
  with_items:
    - AutomaticCheckEnabled
    - AutomaticDownload
    - AutomaticallyInstallMacOSUpdates
    - ConfigDataInstall
    - CriticalUpdateInstall

- name: Disable Spotlight indexing for root
  become: true
  command: mdutil -i off /

- name: Disable hibernate
  become: true
  command: pmset hibernatemode 0

- name: Disable App Sleep for admin user
  osx_defaults:
    key: NSAppSleepDisabled
    type: bool
    value: true

- name: Disable screensaver password for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: askForPassword
    type: bool
    value: false

- name: Disable screensaver for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: 0

- name: Disable save session on logout and restore on login for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.loginwindow
    key: TALLogoutSavesState
    type: int
    value: 0
