---
# Executes systemsetup on macos to change variable
# Vars:
# * key - name of the variable (without "--set" prefix)
# * value - value to set


- name: Set {{ key }} to {{ value }}
  command: systemsetup -set{{ key }} {{ value }}
  become: true
