---
- name: Set GMT timezone
  include_tasks: macos_systemsetup.yml
  vars:
    key: timezone
    value: GMT

- name: Disable system sleep
  include_tasks: macos_systemsetup.yml
  vars:
    key: "{{ item }}"
    value: 0
  with_items:
    - sleep
    - computersleep
    - displaysleep
    - harddisksleep

- name: Disable automatic download and install of the updates
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: "{{ item }}"
    type: bool
    value: false
  with_items:
    - AutomaticCheckEnabled
    - AutomaticDownload
    - AutomaticallyInstallMacOSUpdates
    - ConfigDataInstall
    - CriticalUpdateInstall

- name: Disable Spotlight indexing for root
  become: true
  command: mdutil -i off /

- name: Disable hibernate
  become: true
  command: pmset hibernatemode 0

- name: Disable App Sleep for admin user
  osx_defaults:
    key: NSAppSleepDisabled
    type: bool
    value: true

- name: Disable screensaver password for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: askForPassword
    type: bool
    value: false

- name: Disable screensaver for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: 0

- name: Disable screensaver on login window
  become: true
  osx_defaults:
    domain: com.apple.screensaver
    key: loginWindowIdleTime
    type: int
    value: 0

- name: Disable save session on logout and restore on login for admin user
  osx_defaults:
    host: currentHost
    domain: com.apple.loginwindow
    key: TALLogoutSavesState
    type: int
    value: 0

# MacOS > 12.3 doesn't have python available, so before cleanup of homebrew we need to install one
- name: Make sure python is installed to allow to run ansible
  include_role:
    name: python

# AWS instances have homebrew installed which we don't need in the base image
- name: Remove homebrew if preinstalled
  become: true
  file:
    path: /opt/homebrew
    state: absent
