---
- name: Set GMT timezone
  include_tasks: macos_systemsetup.yml
  vars:
    key: timezone
    value: GMT

- name: Disable sleep
  include_tasks: macos_systemsetup.yml
  vars:
    key: "{{ item }}"
    value: Never
  with_items:
    - computersleep
    - displaysleep
    - harddisksleep

- name: Disable hibernate
  command: pmset hibernatemode 0
  become: true
  changed_when: true

- name: Disable App Sleep
  osx_defaults:
    key: NSAppSleepDisabled
    type: bool
    value: true

- name: Disable screensaver password
  osx_defaults:
    host: currentHost
    domain: com.apple.screensaver
    key: askForPassword
    type: bool
    value: false

- name: Disable automatic update check
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 0
  become: true

- name: Disable Spotlight indexing for root
  command: mdutil -i off /
  become: true
  changed_when: true
