---
# PSTools contains useful psexec which allows to run apps in interactive (GUI) mode

- name: Download PSTools executable to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ init_pstools_win_download_url }}'
    download_sum: '{{ init_pstools_win_download_sum }}'

- name: Unzip the PSTools archive
  win_unzip:
    src: '{{ download_path }}'
    dest: C:\util\pstools
    creates: C:\util\pstools\PsExec.exe
