---
- name: Install pstools to execute in interactive mode
  import_tasks: windows_pstools.yml

- name: Install sdelete to compact the disk
  import_tasks: windows_sdelete.yml

- name: Run optimizations
  import_tasks: windows_osot.yml
  tags:
    - win_init_osot

- name: Disable Administrator local user account
  win_shell: Disable-LocalUser Administrator
  tags:
    - win_init_disable_admin
