---
# SDelete is cleanup tool for compaction of the image

- name: Download SDelete executable to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ init_sdelete_download_url }}'
    download_checksum: '{{ init_sdelete_download_checksum }}'

- name: Unzip the SDelete archive
  win_unzip:
    src: '{{ download_path }}'
    dest: C:\util\sdelete
    creates: C:\util\sdelete\sdelete.exe
