---
# VMWare OS Optimization Tool to prepare the windows image for use

- name: Download OSOT executable to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ init_osot_win_download_url }}'
    download_sum: '{{ init_osot_win_download_sum }}'

- name: Copy OSOT generalize answers
  win_copy:
    src: osot-generalize-answers.xml
    dest: C:\tmp\osot-generalize-answers.xml

# The next commands will mess up with the network interface, so need
# to execute them and after they are completed restart the system
# In finalize we skipping 3, because it causes tool freeze and 7 8 due to no tool available
- name: Create bat file to execute in the background
  win_copy:
    content: >
      echo started > C:\tmp\osot_status.txt

      {{ download_path }} -v -optimize
      -VisualEffect Performance
      -Notification Disable
      -WindowsUpdate Disable
      -OfficeUpdate Disable
      -StoreApp Remove-all
      -Background "#000000"
      -Firewall Disable
      -Antivirus Disable
      -SecurityCenter Disable
      -SmartScreen Disable
      -HVCI Disable
      > C:\tmp\osot_opt.log 2>&1

      {{ download_path }} -v
      -Generalize C:\tmp\osot-generalize-answers.xml
      > C:\tmp\osot_gen.log 2>&1

      {{ download_path }} -v
      -Finalize 0 1 2 4 5 6 9 10 11
      > C:\tmp\osot_fin.log 2>&1

      echo completed > C:\tmp\osot_status.txt

      shutdown /r /t 1
    dest: C:\tmp\execute_osot_reboot.bat

# This command will stall until the system will be rebooted, so will
# fail with "Unexpected failure during module execution" error and it's ok.
# Later we validate the logs out of OSOT tool, so can make sure it was executed properly
- name: Run OSOT optimization, generalization and finalization
  win_psexec:
    executable: C:\util\pstools\PsExec.exe
    interactive: true
    command: C:\tmp\execute_osot_reboot.bat

# VM will reboot and restore winrm connection
- name: Wait for winrm connection
  wait_for_connection:

- name: Check the OSOT process is completed
  win_wait_for:
    path: C:\tmp\osot_status.txt
    regex: completed

- name: Get log from OSOT optimization
  register: reg_osot_opt_log
  win_shell: type C:\tmp\osot_opt.log

- name: Show OSOT optimization log
  debug:
    var: reg_osot_opt_log.stdout_lines

- name: Get log from OSOT generalization
  register: reg_osot_gen_log
  win_shell: type C:\tmp\osot_gen.log

- name: Show OSOT generalization log
  debug:
    var: reg_osot_gen_log.stdout_lines

- name: Get log from OSOT finalization
  register: reg_osot_fin_log
  win_shell: type C:\tmp\osot_fin.log

- name: Show OSOT finalization log
  debug:
    var: reg_osot_fin_log.stdout_lines

# Validate the OSOT logs to contain the necessary lines - this way we
# make sure the optimization was executed properly and not fail somewhere
- name: Verify OSOT opt log
  when: item not in reg_osot_opt_log.stdout_lines
  fail:
    msg: OSOT opt log does not contains the required line "{{ item }}"
  with_items:
    - Turn off Windows Antimalware - Machine Policy
    - Disable Behavior Monitoring - Machine Policy
    - Disable On Access Protection - Machine Policy
    - Disable Realtime Scan - Machine Policy
    - Disable defender antivirus service - Service
    - Disable Windows Defender Verification - Scheduled Task
    - Disable All Firewall Profiles - Command
    - Adjust for best performance - HKLM Registry
    - Disable Windows Search - Service
    - Optimization is done.

- name: Verify OSOT gen log
  when: item not in reg_osot_gen_log.stdout_lines
  fail:
    msg: OSOT gen log does not contains the required line "{{ item }}"
  with_items:
    - Generalize is done, please reboot your computer.

- name: Verify OSOT fin log
  when: item not in reg_osot_fin_log.stdout_lines
  fail:
    msg: OSOT fin log does not contains the required line "{{ item }}"
  with_items:
    - Finalize is done.
