---
- name: Download NodeJS archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ nodejs_mac_download_url }}'
    download_checksum: '{{ nodejs_mac_download_checksum }}'

- name: Create extract directory
  become: true
  file:
    path: /usr/local/nodejs
    state: directory

# Uses BSD tar, GNU will require --wildcards in addition
- name: Unpack only bin & lib from archive to directory
  become: true
  command: tar -C "/usr/local/nodejs" --strip-components=1 -xf "{{ download_path }}"
  args:
    warn: false  # Unarchive requires GNU tar that is not installed on macos by default

- name: Check binaries was unpacked properly
  stat:
    path: /usr/local/nodejs/bin/{{ item }}
  register: reg_nodejs_bin_file
  failed_when: not reg_nodejs_bin_file.stat.exists
  loop:
    - node
    - npm

- name: Create symlinks
  become: true
  file:
    src: /usr/local/nodejs/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - node
    - npm
