---
# Installs Features on Demand needed by Windows 2019 to install OpenSSH

- name: Download FOD iso to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ openssh_server_fod_win_download_url }}'
    download_checksum: '{{ openssh_server_fod_win_download_checksum }}'

- name: Mount the FOD iso as a disk
  win_shell: (Mount-DiskImage -ImagePath "{{ download_path }}" | Get-Volume).DriveLetter
  register: reg_fod_drive_letter

- name: Copy FOD files to fod directory
  win_shell: 'Copy-Item {{ reg_fod_drive_letter.stdout_lines | first }}: C:\tmp\fod -Recurse'

- name: Umount the FOD iso disk
  win_shell: Dismount-DiskImage -ImagePath "{{ download_path }}"
