---
- name: Install python with pip and venv
  become: true
  environment:
    # Redirecting APT requests through proxy
    http_proxy: "{{ bait_proxy_url | default(omit) }}"
    https_proxy: "{{ bait_proxy_url | default(omit) }}"
  apt:
    update_cache: true
    name:
      - python3
      - python3-pip
      - python3-venv
      - python-is-python3

- name: Verify python binary is here
  command: python --version  # noqa 303
