---
- name: Download python pkg to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ python_mac_download_url }}'
    download_sum: '{{ python_mac_download_sum }}'

- name: Install python from pkg
  become: true
  command: installer -pkg '{{ download_path }}' -target /

- name: Create a symbolic link for python to python3
  become: true
  file:
    src: /usr/local/bin/python3
    dest: /usr/local/bin/python
    owner: root
    group: wheel
    state: link

- name: Verify python binary is here
  command: /usr/local/bin/python --version  # noqa 303
