---
- name: Download python installer to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ python_win_download_url }}'
    download_checksum: '{{ python_win_download_checksum }}'

- name: Install python to util dir
  win_command: '{{ download_path }} /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 TargetDir=C:\util\python3'

- name: Check python binary was installed properly
  win_command: C:\util\python3\python.exe --version
