---
- name: Install git basic tools
  become: true
  environment:
    # Redirecting APT requests through proxy
    http_proxy: "{{ bait_proxy_url | default(omit) }}"
    https_proxy: "{{ bait_proxy_url | default(omit) }}"
  apt:
    update_cache: true
    name:
      - git-core

- name: Verify git binary was installed properly
  command: git --version  # noqa 303
