---
- name: Download Git installer to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ git_win_download_url }}'
    download_checksum: '{{ git_win_download_checksum }}'

- name: Install git to util folder
  win_command: '{{ download_path }} /VERYSILENT /NORESTART /SP- /NOCANCEL /SUPPRESSMSGBOXES /DIR=C:\util\git'

- name: Enable OpenSSH agent to run
  win_service:
    name: ssh-agent
    start_mode: auto
    state: stopped

- name: Add git bin dir to system PATH
  win_path:
    elements: C:\util\git\bin

- name: Check git binary was installed properly
  win_command: C:\util\git\bin\git --version
