---
- name: Get JDK on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ jdk_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ jdk_archive_local }}"
        dest: /tmp/{{ jdk_archive_local }}

    - name: Download archive if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ jdk_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ jdk_archive_local }}"
        mode: "0440"
        checksum: "{{ jdk_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ jdk_archive_local }}"
        dest: /tmp/{{ jdk_archive_local }}

- name: Mount JDK DMG file
  command: hdiutil attach '/tmp/{{ jdk_archive_local }}' -nobrowse -mountpoint /tmp/jdk
  become: true
  changed_when: true

- name: Install JDK from mounted DMG volume
  shell: installer -pkg /tmp/jdk/*.pkg -target /
  become: true
  changed_when: true

- name: Umount JDK DMG file
  become: true
  command: hdiutil detach /tmp/jdk
  changed_when: true
