---
- name: Download JDK DMG to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ jdk_mac_download_url }}'
    download_checksum: '{{ jdk_mac_download_checksum }}'

- name: Mount JDK DMG file
  command: hdiutil attach '{{ download_path }}' -nobrowse -mountpoint /tmp/jdk
  become: true

- name: Install JDK from mounted DMG volume
  shell: installer -pkg /tmp/jdk/*.pkg -target /
  become: true

- name: Umount JDK DMG file
  become: true
  command: hdiutil detach /tmp/jdk
