---
- name: Execute on Linux
  include_tasks: linux.yml
  when: ansible_system == 'Linux'

- name: Execute on MacOS
  when: ansible_system == 'Darwin'
  import_tasks: macos.yml

- name: Execute on Windows
  include_tasks: windows.yml
  when: ansible_system == 'Win32NT'
