---
- name: Download groovy archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ groovy_download_url }}'
    download_checksum: '{{ groovy_download_checksum }}'

- name: Unzip groovy
  become: true
  register: reg_groovy_unpacked
  unarchive:
    src: '{{ download_path }}'
    dest: /usr/local
    remote_src: true
    list_files: true

- name: Create bin directory
  become: true
  file:
    path: /usr/local/bin
    state: directory

- name: Create symlink
  become: true
  file:
    src: /usr/local/{{ (reg_groovy_unpacked.files | first).split("/") | first }}/bin/groovy
    dest: /usr/local/bin/groovy
    state: link
