---
- name: Validate required variables
  when: item not in vars or vars[item] | length == 0
  with_items: "{{ required_vars }}"
  fail:
    msg: Variable '{{ item }}' is not defined

- name: Execute on MacOS
  when: ansible_system == 'Darwin'
  import_tasks: macos.yml
