---
cmake_mac_download_url: https://artifact-storage/aquarium/files/mac/cmake-3.20.5-macos-universal.tar.gz
cmake_mac_download_checksum: sha256:000828af55268853ba21b91f8ce3bfb9365aa72aee960fc7f0c01a71f3a2217a
cmake_lin_download_url: https://artifact-storage/aquarium/files/lin/cmake-3.20.5-linux-x86_64.sh
cmake_lin_download_checksum: sha256:f582e02696ceee81818dc3378531804b2213ed41c2a8bc566253d16d894cefab
