---
- name: Check System Integrity Protection - we don't need it in CI system
  import_tasks: macos_check_sip.yml

- name: Disable not needed services
  command: launchctl unload -w /System/Library/{{ item }}
  become: true
  with_items:
    - LaunchDaemons/com.apple.metadata.mds.plist  # Spotlight service (too much load on disk)
    - LaunchDaemons/com.apple.netbiosd.plist  # Netbios - No need to much net fuzz
    - LaunchDaemons/com.apple.apsd.plist  # No push notifications
    - LaunchAgents/com.apple.imagent.plist  # Facetime - no need it
    - LaunchAgents/com.apple.CalendarAgent.plist  # No need it anyhow

- name: Disable mitigations (Spectre, Meltdown) to increase performance
  become: true
  # MacOS Monterey have this option read only, so no luck
  ignore_errors: '{{ ansible_distribution_major_version | int >= 12  }}'
  sysctl:
    name: kern.hv.vmx_mitigations
    value: '0'
    state: present
    reload: false  # Not working on macos
    sysctl_set: true  # To set the value on macos

# Tools uses /usr/local/bin to place the executables
- name: Set /usr/local/bin directory in PATH for the entire system
  become: true
  command: launchctl config "{{ item }}" path "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  with_items:
    - system  # Will work for shh and system LaunchDaemons
    - user  # Will work for user LaunchAgents too

- name: Install rosetta to support x86 binaries on ARM devices
  become: true
  include_role:
    name: rosetta
  when:
    - ansible_facts.architecture == 'arm64'
    - init_ci_mac_install_rosetta|bool
