---
- name: Get System Integrity Protection status
  command: csrutil status
  become: true
  changed_when: false
  register: reg_csrstatus

- name: Print csrstatus configuration
  debug:
    var: reg_csrstatus.stdout_lines

- name: Validate System Integrity Protection status
  when: "reg_csrstatus.stdout.endswith('status: enabled.')"
  fail:
    msg: "The System Integrity Protection is enabled."
