---
- name: Get System Integrity Protection status
  become: true
  command: csrutil status
  register: reg_csrstatus

- name: Print csrstatus configuration
  debug:
    var: reg_csrstatus.stdout_lines

- name: Validate System Integrity Protection status
  when: "not reg_csrstatus.stdout.endswith('status: enabled.')"
  fail:
    msg: The System Integrity Protection is disabled which is bad
