---
- name: Get ccache on VM
  block:
    - name: Create archive directory
      file:
        path: /tmp/{{ ccache_archive_local | dirname }}
        state: directory

    - name: Get archive from the localhost files
      ignore_errors: true
      register: reg_copy_local_file
      copy:
        src: "{{ ccache_archive_local }}"
        dest: /tmp/{{ ccache_archive_local }}

    - name: Download archive if local file is not available
      when: reg_copy_local_file.failed
      delegate_to: localhost
      get_url:
        url: "{{ ccache_archive_url }}"
        dest: "{{ playbook_dir }}/files/{{ ccache_archive_local }}"
        mode: "0440"
        checksum: "{{ ccache_archive_checksum }}"

    - name: Get archive from the localhost files
      when: reg_copy_local_file.failed
      copy:
        src: "{{ ccache_archive_local }}"
        dest: /tmp/{{ ccache_archive_local }}

# Build & install ccache
- name: Create build directory
  file:
    path: /tmp/ccache_build
    state: directory

- name: Unzip ccache
  changed_when: true
  command: tar --strip-components=1 -xf /tmp/{{ ccache_archive_local }} -C /tmp/ccache_build
  args:
    warn: false  # Unarchive requires GNU tar that is not installed on macos by default

- name: Run configure for ccache
  changed_when: true
  command: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/ccache_build

- name: Build ccache
  changed_when: true
  command: make
  args:
    chdir: /tmp/ccache_build

- name: Install ccache
  become: true
  changed_when: true
  command: make install
  args:
    chdir: /tmp/ccache_build

- name: Check the ccache is installed properly
  stat:
    path: /usr/local/bin/ccache
  register: reg_ccache_bin_file
  failed_when: not reg_ccache_bin_file.stat.exists
