---
min_packer_version: 1.7.9
variables:
  # All the variables are set by the build_image.sh script based on the path
  image_name: image
  out_full_path: "{{ env `PWD` }}/out"

builders:
  - type: docker
    image: ubuntu:22.04
    commit: true

provisioners:
  # Install python3 to connect by ansible from host machine in child images
  - type: shell
    inline:
      - apt update
      - apt install -y python3 python-is-python3
      # Cleanup
      - apt -qq clean
      - rm -rf /var/lib/apt/lists/*

post-processors:
  - type: docker-tag
    repository: "aquarium/{{ user `image_name` }}"
    tags: original
