---
init_pstools_download_url: https://artifact-storage/aquarium/files/win/PSTools/PSTools-v2.48.zip
init_pstools_download_checksum: sha256:102576f2df817427fee2804380ef8904afb7b46d73d56d1a60e7721d668b6555

init_sdelete_download_url: https://artifact-storage/aquarium/files/win/SDelete/SDelete-v2.04.zip
init_sdelete_download_checksum: sha256:49cfc704a431d0f4557d06561310ade7ba78b84c389a99cbe0fac83410f6b255

init_osot_download_url: https://artifact-storage/aquarium/files/win/VMwareHorizonOSOptimizationTool-x86_64-2107.exe
init_osot_download_checksum: sha256:c6db0f134296853755bd6cb083b1fcbbe177b52059b4434e81e24b013978fb12
