---
xcode_version_122_mac_download_url: https://artifact-storage/aquarium/app/mac/Xcode_12.2.xip
xcode_version_122_mac_download_sum: sha256:28d352f8c14a43d9b8a082ac6338dc173cb153f964c6e8fb6ba389e5be528bd0
xcode_version_122_cmd_mac_download_url: https://artifact-storage/aquarium/app/mac/Command_Line_Tools_for_Xcode_12.2.dmg
xcode_version_122_cmd_mac_download_sum: sha256:3911b66247e030c7210940cde4230319058bc5c55a81627b8853dab644092c40

xcode_version_131_mac_download_url: https://artifact-storage/aquarium/files/mac/Xcode_13.1.xip
xcode_version_131_mac_download_sum: sha256:4efdeea0eeeda1957bb394128cccd1daac3cb0a3d074224e0fab90855cca09c4
xcode_version_131_cmd_mac_download_url: https://artifact-storage/aquarium/files/mac/Command_Line_Tools_for_Xcode_13.1.dmg
xcode_version_131_cmd_mac_download_sum: sha256:9a64702299c0fce068c729fbeb316705afd810c5812f83a180a9cccfc5ae4e00

xcode_version_133_mac_download_url: https://artifact-storage/aquarium/files/mac/Xcode_13.3.xip
xcode_version_133_mac_download_sum: sha256:dc5fd115b0e122427e2a82b3fbd715c3aee49ef76a64c4d1c59a787ce17a611b
xcode_version_133_cmd_mac_download_url: https://artifact-storage/aquarium/files/mac/Command_Line_Tools_for_Xcode_13.3.dmg
xcode_version_133_cmd_mac_download_sum: sha256:7eff583b5ce266cde5c1c8858e779fcb76510ec1af3d9d5408c9f864111005c3

xcode_version_143_mac_download_url: https://artifact-storage/aquarium/files/mac/Xcode_14.3.xip
xcode_version_143_mac_download_sum: sha256:aba7ab7dfe4ce5f1134ac757dc6e61d769bd84d93b75eb245a1a6ed3fa95fdae
xcode_version_143_cmd_mac_download_url: https://artifact-storage/aquarium/files/mac/Command_Line_Tools_for_Xcode_14.3.dmg
xcode_version_143_cmd_mac_download_sum: sha256:91bb2c727d2861e69cdb779fbc0d794dd6f3ad2c9c7b5c9a5e985e2aff7cd22b

xcode_version_151_mac_download_url: https://artifact-storage/aquarium/files/mac/Xcode_15.1.xip
xcode_version_151_mac_download_sum: sha256:857d8db537bac82bf99de0e1d3895d214d4d02101c1340cef3daf6e821ba1d05
xcode_version_151_cmd_mac_download_url: https://artifact-storage/aquarium/files/mac/Command_Line_Tools_for_Xcode_15.1.dmg
xcode_version_151_cmd_mac_download_sum: sha256:690c1a1f9e966a8669a1b8b3af6d3a0858fafeee16136fe985bf1d00eb54b425
