---
- name: Execute on Linux
  include_tasks: linux.yml
  when: ansible_system == 'Linux' and ansible_service_mgr == 'systemd'

- name: Execute on MacOS
  include_tasks: macos.yml
  when: ansible_system == 'Darwin'

- name: Execute on Windows
  include_tasks: windows.yml
  when: ansible_system == 'Win32NT'
