---
- name: Add jenkins group
  become: true
  group:
    name: jenkins
    gid: 5001

- name: Add user jenkins with group jenkins
  become: true
  user:
    name: jenkins
    group: jenkins
    uid: 5001
    comment: Jenkins

- name: Install tools required by jenkins_agent.sh script
  become: true
  environment:
    # Redirecting APT requests through proxy
    http_proxy: "{{ bait_proxy_url | default(omit) }}"
    https_proxy: "{{ bait_proxy_url | default(omit) }}"
  apt:
    update_cache: true
    name:
      - iproute2
      - curl

- name: Create extract directory
  become: true
  file:
    path: "{{ jenkins_agent_path }}"
    state: directory

- name: Store jenkins agent executable scripts
  become: true
  copy:
    src: lin/jenkins_agent.sh
    dest: "{{ jenkins_agent_path }}/jenkins_agent.sh"
    owner: root
    group: root
    mode: "0755"

- when: ansible_service_mgr == 'systemd'
  block:
    - name: Add jenkins-agent systemd service
      become: true
      template:
        src: jenkins-agent.service.j2
        dest: /etc/systemd/system/jenkins-agent.service
        owner: root
        group: root
        mode: "0644"
      vars:
        java_home: "{{ jenkins_agent_java_home }}"
        config_url: "{{ jenkins_agent_config_url }}"
        script_path: "{{ jenkins_agent_path }}/jenkins_agent.sh"

    - name: Enable service to start the jenkins agent on boot
      become: true
      service:
        name: jenkins-agent
        enabled: true
        state: stopped

    - name: Store disk scripts
      become: true
      copy:
        src: lin/{{ item }}.sh
        dest: "{{ jenkins_agent_path }}/{{ item }}.sh"
        owner: root
        group: root
        mode: "0755"
      loop:
        - mountall
        - formatall

    - name: Store service unit file for disk scripts autorun
      become: true
      template:
        src: script.service.j2
        dest: /etc/systemd/system/{{ item }}.service
        owner: root
        group: root
        mode: "0644"
      vars:
        script_name: "{{ item }}"
        script_path: "{{ jenkins_agent_path }}/{{ item }}.sh"
      loop:
        - mountall
        - formatall

    - name: Enable service to start the disk scripts on boot
      become: true
      service:
        name: "{{ item }}"
        enabled: true
        state: stopped
      loop:
        - mountall
        - formatall
