---
- name: Add jenkins group
  become: true
  group:
    name: jenkins
    gid: 5001

- name: Add user jenkins with group jenkins
  become: true
  user:
    name: jenkins
    group: jenkins
    uid: 5001
    comment: Jenkins

- name: Create extract directory
  become: true
  file:
    path: /opt/srv/jenkins_agent
    state: directory

- name: Store jenkins agent executable scripts
  become: true
  copy:
    src: mac/jenkins_agent.sh
    dest: /opt/srv/jenkins_agent/jenkins_agent.sh
    owner: root
    group: wheel
    mode: "0755"

- name: Store service plist file for agent autorun
  become: true
  template:
    src: aquarium.ci.agent.plist.j2
    dest: /Library/LaunchDaemons/aquarium.ci.agent.plist
    owner: root
    group: wheel
    mode: "0644"
  vars:
    java_home: "{{ jenkins_agent_java_home }}"
    script_path: /opt/srv/jenkins_agent/jenkins_agent.sh

- name: Store mountall executable scripts
  become: true
  copy:
    src: mac/mountall.sh
    dest: /opt/srv/jenkins_agent/mountall.sh
    owner: root
    group: wheel
    mode: "0755"

- name: Store service plist file for mountall autorun
  become: true
  template:
    src: aquarium.ci.mountall.plist.j2
    dest: /Library/LaunchDaemons/aquarium.ci.mountall.plist
    owner: root
    group: wheel
    mode: "0644"
  vars:
    script_path: /opt/srv/jenkins_agent/mountall.sh
