---
- name: VS will be installed to the next directory
  when: visualstudio_install_path | length > 0
  debug:
    var: visualstudio_install_path

- name: Download Visual Studio archive to the environment
  include_role:
    name: download
  vars:
    download_url: '{{ visualstudio_download_url }}'
    download_checksum: '{{ visualstudio_download_checksum }}'

- name: Unzip the VisualStudio archive
  win_unzip:
    src: '{{ download_path }}'
    dest: C:\tmp\vs

- name: Detect the visual studio install certificates
  win_find:
    paths: C:\tmp\vs
    patterns: '*.cer'
    recurse: true
  register: reg_vs_install_certs
  failed_when: reg_vs_install_certs.matched < 1

- name: Register VisualStudio Install Certificates
  win_certificate_store:
    file_type: der
    store_location: LocalMachine
    store_name: Root
    state: present
    path: "{{ item.path }}"
  with_items: '{{ reg_vs_install_certs.files }}'

- name: Locate the visual studio installer
  win_find:
    paths: C:\tmp\vs
    patterns: vs_setup.exe
    recurse: true
  register: reg_vs_installer_path
  failed_when: reg_vs_installer_path.matched != 1

- name: Locate the visual studio installer Response answers
  win_find:
    paths: C:\tmp\vs
    patterns: vs*.json
  register: reg_vs_installer_answers
  failed_when: reg_vs_installer_answers.matched != 1

- name: Copy the response answers to installer directory
  win_copy:
    src: '{{ (reg_vs_installer_answers.files | first).path }}'
    dest: '{{ (reg_vs_installer_path.files | first).path | win_dirname }}\Response.json'
    remote_src: true

# In case it fails - you can check the log file:
# C:\Users\packer\AppData\Local\Temp\dd_installer_<datetime>.log
- name: Install VisualStudio
  win_command: >
    {{ (reg_vs_installer_path.files | first).path }}
    --in "{{ (reg_vs_installer_path.files | first).path | win_dirname }}\Response.json"
    {% if visualstudio_install_path %}--installPath "{{ visualstudio_install_path }}"{% endif %}
    --noRestart --noWeb --force --quiet --wait

# The var will not be set until the install directory is defined - we don't need
# to deal with the complicated heuristics trying to determine where installer
# put the visual studio files
- when: visualstudio_install_path | length > 0
  block:
    - name: Check the VS was installed correctly
      win_stat:
        path: '{{ visualstudio_install_path }}\{{ item }}'
      with_items:
        - Common7\IDE\devenv.exe
        - Common7\IDE\Extensions\TestPlatform\vstest.console.exe
        - MSBuild\Current\Bin\MSBuild.exe
        - VC\Auxiliary\Build\vcvars64.bat
      register: reg_stat_file
      failed_when: not reg_stat_file.stat.exists

    - name: Set system env variable of VS location
      win_environment:
        level: machine
        state: present
        name: VS_LOCATION
        value: '{{ visualstudio_install_path }}'
