---
- name: Install unzip
  become: true
  environment:
    # Redirecting APT requests through proxy
    http_proxy: "{{ bait_proxy_url | default(omit) }}"
    https_proxy: "{{ bait_proxy_url | default(omit) }}"
  apt:
    update_cache: true
    name:
      - unzip

- name: Verify unzip binary was installed properly
  command: unzip -v  # noqa 303
