---
- name: Base image provision
  hosts: all
  tasks:
    - include_role:
        name: init

    - when: vmtools_vm_type is defined
      include_role:
        name: vmtools  # It's critical for appleGPU to install tools in the first OS boot

    - include_role:
        name: cleanup
