---
- name: Native CI image provision
  hosts: all
  vars:
    # Set dirs to the native_platform because we're using only lin/mac as host machine
    download_lin_dir: '{{ native_platform }}'
    download_mac_dir: '{{ native_platform }}'
    java_extract_path: '{{ native_init_path }}/srv/jre8'
  tasks:
    - include_role:
        name: java
      vars:
        java_download_url: "{{ lookup('vars', 'java_'+native_platform+'_download_url') }}"
        java_download_sum: "{{ lookup('vars', 'java_'+native_platform+'_download_sum') }}"
        java_tar_suffix: "{{ lookup('vars', 'java_'+native_platform+'_tar_suffix') }}"

    - include_role:
        name: jenkins_agent
        tasks_from: native
      vars:
        jenkins_agent_path: '{{ native_init_path }}/srv/jenkins_agent'
