name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Check-Lin-VMX:
    runs-on: ubuntu-latest
    steps:
      - name: Setup VMWare Workstation
        run: |
          sudo apt update && sudo apt-get install -y build-essential linux-headers-$(uname -r) gcc qemu-utils libxi6 libgconf-2-4 libxinerama1 libxcursor-dev libxtst6
          curl -Lo vmware-workstation.bundle https://download3.vmware.com/software/WKST-1702-LX/VMware-Workstation-Full-17.0.2-21581411.x86_64.bundle
          sudo bash vmware-workstation.bundle --console --eulas-agreed --required

      - uses: actions/checkout@v3

      - name: Test
        run: |
          vmrun -T ws list
          curl -Lo init/iso/ubuntu-20.04.4-live-server-amd64.iso https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso
          ./build_image.sh specs/vmx/ubuntu2004.yml

  Check-Mac-VMX:
    runs-on: macos-12
    steps:
      - name: Setup VMWare Fusion
        run: |
          brew install vmware-fusion

      - name: Test
        run: |
          vmrun -T fusion list
