name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run checkstyle
        run: ./check_style.sh

      - name: Run docker image build validation
        run: |
          export BAIT_SPEC_CHANGE='{"provisioners":[{"playbook_file": "{{ user `bait_path` }}/playbooks/bait_validate.yml"}]}'
          for spec in $(find ./specs/docker -name '*.yml' | sort); do
            ./build_image.sh "${spec}"
          done
